version: "3"

services:
  backend:
    image: eggheadiofree
    container_name: eggheadiofree
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/home/node/app
    ports:
      - 3000:3000
    tty: true
