name: Deploy website

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js for Bot
      uses: actions/setup-node@v3.1.1
      with:
        node-version: 18
    - name: Run bot
      working-directory: bot
      run: |
        npm install
        mkdir output
        npx ts-node --transpile-only src/index.ts > output/cleanCourses.json
    - name: Run Next.js build and export
      working-directory: frontend-tailwind
      run: |
        npm install
        npm run build
        npx next export
    - name: rsync deploy
      uses: Burnett01/rsync-deployments@5.2
      with:
        switches: -avh --delete
        path: frontend-tailwind/out/
        remote_path: ${{secrets.REMOTE_PATH}}
        remote_host: ${{secrets.REMOTE_HOST}}
        remote_user: ${{secrets.REMOTE_USER}}
        remote_key: ${{secrets.SSH_PRIVATE_KEY}}
        
