name: Deploy website

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Enter bot
      run: cd bot
    - name: Use Node.js
      uses: actions/setup-node@v3.1.1
      with:
        node-version: 16
        cache: npm
    - name: Run bot
      run: |
        npm install
        mkdir output
        npx ts-node --transpile-only src/index.ts > output/cleanCourses.json
    - name: Location
      run: ls
