name: Deploy website

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js for Bot
      uses: actions/setup-node@v3.1.1
      with:
        node-version: 16
        cache: npm
        cache-dependency-path: bot/package-lock.json
    - name: Run bot
      working-directory: bot
      run: |
        npm install
        mkdir output
        npx ts-node --transpile-only src/index.ts > output/cleanCourses.json
    - name: Location
      working-directory: bot
      run: ls
    - name: Setup Node.js for Next.js
      uses: actions/setup-node@v3.1.1
      with:
        node-version: 16
        cache: npm
        cache-dependency-path: frontend-tailwind/package-lock.json
    - name: Run Next.js build and export
      working-directory: frontend-tailwind
      run: |
        npm install
        npm run build
        npx next export
        ls
        
